### ISSUE TITLE
Null pointer exception

### ISSUE THREAD

**Issue by bjhoohaha** [AY1920S1-CS2103T-T17-2/main#152]
``````
INFO: =============================[ Initializing AddressBook ]===========================
Nov 04, 2019 5:04:12 PM seedu.address.MainApp initConfig
INFO: Using config file : config.json
Nov 04, 2019 5:04:12 PM seedu.address.MainApp initPrefs
INFO: Using prefs file : preferences.json
Nov 04, 2019 5:04:12 PM seedu.address.commons.core.LogsCenter init
INFO: currentLogLevel: INFO
Nov 04, 2019 5:04:12 PM seedu.address.diaryfeature.storage.JsonDiaryBookStorage readDiaryBook
INFO: using written book
Nov 04, 2019 5:04:12 PM seedu.address.MainApp start
INFO: Starting AddressBook V0.6.0ea
Nov 04, 2019 5:04:12 PM seedu.address.ui.UiManager start
INFO: Starting UI...
Nov 04, 2019 5:04:12 PM seedu.address.ui.UiManager start
SEVERE: null
java.lang.NullPointerException
	at seedu.address.financialtracker.model.FinancialTracker.addExpense(FinancialTracker.java:72)
	at seedu.address.financialtracker.storage.JsonSerializableFinancialTracker.toModelType(JsonSerializableFinancialTracker.java:59)
	at seedu.address.financialtracker.storage.JsonFinancialTrackerStorage.readFinancialTracker(JsonFinancialTrackerStorage.java:55)
	at seedu.address.financialtracker.storage.JsonFinancialTrackerStorage.readFinancialTracker(JsonFinancialTrackerStorage.java:36)
	at seedu.address.financialtracker.logic.FinancialTrackerLogic.<init>(FinancialTrackerLogic.java:36)
	at seedu.address.financialtracker.ui.FinancialTrackerPage.<init>(FinancialTrackerPage.java:74)
	at seedu.address.ui.MainWindow.<init>(MainWindow.java:95)
	at seedu.address.ui.UiManager.start(UiManager.java:41)
	at seedu.address.MainApp.start(MainApp.java:180)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)

Nov 04, 2019 5:04:12 PM seedu.address.ui.UiManager showFatalErrorDialogAndShutdown
SEVERE: Fatal error during initializing nullnull
java.lang.NullPointerException
	at seedu.address.financialtracker.model.FinancialTracker.addExpense(FinancialTracker.java:72)
	at seedu.address.financialtracker.storage.JsonSerializableFinancialTracker.toModelType(JsonSerializableFinancialTracker.java:59)
	at seedu.address.financialtracker.storage.JsonFinancialTrackerStorage.readFinancialTracker(JsonFinancialTrackerStorage.java:55)
	at seedu.address.financialtracker.storage.JsonFinancialTrackerStorage.readFinancialTracker(JsonFinancialTrackerStorage.java:36)
	at seedu.address.financialtracker.logic.FinancialTrackerLogic.<init>(FinancialTrackerLogic.java:36)
	at seedu.address.financialtracker.ui.FinancialTrackerPage.<init>(FinancialTrackerPage.java:74)
	at seedu.address.ui.MainWindow.<init>(MainWindow.java:95)
	at seedu.address.ui.UiManager.start(UiManager.java:41)
	at seedu.address.MainApp.start(MainApp.java:180)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
````





````

{
  "expenses" : [ {
    "date" : "03122019",
    "time" : "2240",
    "amount" : "1200",
    "description" : "Universal Studios Ticket",
    "type" : "entertainment",
    "country" : "Japan "
  }, {
    "date" : "03122019",
    "time" : "2240",
    "amount" : "1200",
    "description" : "test",
    "type" : "sdfsd",
    "country" : "Singapore"
  }, {
    "date" : "04122019",
    "time" : "1701",
    "amount" : "1200",
    "description" : "food",
    "type" : "food",
    "country" : "Singapore"
  } ]
}
````

**Comment by bjhoohaha** [comment]
Bug fixed
